const example = {
  wol12: {
    id: 391,
    "file-name": "wol12",
    name: {
      "name-USen": "Audie",
      "name-EUen": "Audie",
      "name-EUde": "Katharina",
      "name-EUfr": "Monica",
      "name-USfr": "Monica",
      "name-EUit": "Lupilia",
      "name-EUnl": "Audie",
    },
    personality: "Peppy",
    "birthday-string": "August 31st",
    birthday: "31/8",
    species: "Wolf",
    gender: "Female",
    subtype: "A",
    hobby: "Fitness",
    "catch-phrase": "foxtrot",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/391",
    image_uri: "https://acnhapi.com/v1/images/villagers/391",
    "bubble-color": "#ff791f",
    "text-color": "#fff2bb",
    saying: "Be the kind of person your future self won't regret having been.",
    "catch-translations": {
      "catch-USen": "foxtrot",
      "catch-EUen": "foxtrot",
      "catch-EUde": "foxtrott",
      "catch-EUes": "maravilla",
      "catch-EUfr": "trottine",
      "catch-USfr": "trottine",
      "catch-EUit": "foxtrot",
      "catch-EUnl": "foxtrot",
    },
  },
  wol12: {
    id: 391,
    "file-name": "wol12",
    name: {
      "name-USen": "Audie",
      "name-EUen": "Audie",
      "name-EUde": "Katharina",
      "name-EUfr": "Monica",
      "name-USfr": "Monica",
      "name-EUit": "Lupilia",
      "name-EUnl": "Audie",
    },
    personality: "Peppy",
    "birthday-string": "August 31st",
    birthday: "31/8",
    species: "Wolf",
    gender: "Female",
    subtype: "A",
    hobby: "Fitness",
    "catch-phrase": "foxtrot",
    icon_uri: "https://acnhapi.com/v1/icons/villagers/391",
    image_uri: "https://acnhapi.com/v1/images/villagers/391",
    "bubble-color": "#ff791f",
    "text-color": "#fff2bb",
    saying: "Be the kind of person your future self won't regret having been.",
    "catch-translations": {
      "catch-USen": "foxtrot",
      "catch-EUen": "foxtrot",
      "catch-EUde": "foxtrott",
      "catch-EUes": "maravilla",
      "catch-EUfr": "trottine",
      "catch-USfr": "trottine",
      "catch-EUit": "foxtrot",
      "catch-EUnl": "foxtrot",
    },
  },
  // ...
};
